#RDIR=Your worksapce directory
bwa=$RDIR/tools/bwa-0.7.16a/bwa
samtools=$RDIR/tools/samtools-1.5/samtools
rtg=$RDIR/tools/rtg-tools-3.8.3/rtg

#Reference file
ref=$RDIR/reference/hg38.fa

REF=${ref%.*}.fa
SDFREF=${REF%.*}.sdf

################## SCRIPT #########################
>&2 date
>&2 echo "making index"
>&2 date && >&2 echo " -> bwa index"
$bwa index $REF
>&2 date && >&2 echo " -> samtools faidx"
$samtools faidx $REF
>&2 date && >&2 echo " -> rtg format sdf"
$rtg format -o $SDFREF $REF
