#!/bin/bash
#$ -pe parallel 4
#$ -cwd -m ea

#PERCORSI TOOLS
RDIR=/nfsd/bcb/bcbg/shibuyay/Tesi

PCOUNT=4

#Reference Files
AFFYREF=$RDIR/reference/affykmers.reassembled.fa
DBSNPREF=$RDIR/reference/dbSNPkmers.reassembled.fa
MITALLREF=$RDIR/reference/mit_all.reassembled.fa

#Input files
INPUT2=$RDIR/working_datasets/SRR622461_2.filt.fastq.gz
INPUT2UNZ=$RDIR/quartz_files/SRR622461_2.filt.fastq

#Output files
OUTPUT2=$RDIR/results/smooth/SRR62_2_smoothed.fastq.gz
OUTPUT2UNZ=$RDIR/results/smooth/SRR62_2_smoothed.fastq
AFFYOUTPUT=$RDIR/results/smooth/SRR62_2_affy_smoothed.fastq.gz
DBSNPOUTPUT=$RDIR/results/smooth/SRR62_2_dbSNP_smoothed.fastq.gz
MITALLOUTPUT=$RDIR/results/smooth/SRR62_2_mit_all_smoothed.fastq.gz

YALFF=$RDIR/executables/yalff

################## SCRIPT #########################
>&2 date
>&2 echo "Inizio script smoothing 2"

zcat $INPUT2 | $YALFF -d $AFFYREF -b \' -t $PCOUNT | gzip > $AFFYOUTPUT
>&2 echo "smoothing affy completato"

zcat $INPUT2 | $YALFF -d $DBSNPREF -b \' -t $PCOUNT | gzip > $DBSNPOUTPUT
>&2 echo "smoothing dbSNP completato"

zcat $INPUT2 | $YALFF -d $MITALLREF -b \' -t $PCOUNT | gzip > $MITALLOUTPUT
>&2 echo "smoothing mit_all completato"

>&2 date
>&2 echo "Fine script smoothing 2" 
